version: '3'
services:
  mongo:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=nest-pokemon
    volumes:
      - ./mongodb_data:/data/db
  app:
    container_name: poke-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${APP_PORT}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - DB_MONGO_URI=${DB_MONGO_URI}
      - APP_PORT=${APP_PORT}
      - CONSTANTS_PAGINATION_LIMIT=${CONSTANTS_PAGINATION_LIMIT}
      - APP_CORS_ORIGIN=${APP_CORS_ORIGIN}
      - APP_CORS_ALLOWEDHEADERS=${APP_CORS_ORIGIN}
    depends_on:
      - mongo
    restart: always
